/**
 * Maps feedback events to their sound-asset file BASENAMES under
 * assets/sounds/ (generated by scripts/generate-sounds.mjs).
 *
 * Why basenames and not `require('../../assets/sounds/make.wav')`: Metro
 * only bundles assets referenced by STATIC require calls (and .wav needs
 * the asset extension configured in metro.config.js). The camera/audio
 * layer therefore keeps its own static `require` table keyed by these
 * basenames, e.g.:
 *
 * ```ts
 * const MODULES = {
 *   [SOUND_FILES.make]: require('../../assets/sounds/make.wav'),
 *   // ...one static line per entry
 * };
 * ```
 *
 * This module stays pure/dependency-free so it can be unit-tested and
 * shared with non-RN tooling.
 */
import type { SoundEvent } from './types';

/** Every key the app can play: pipeline SoundEvents plus app-lifecycle cues. */
export type AppSoundKey = SoundEvent | 'session_start' | 'rim_locked';

/**
 * Sound file basenames (relative to assets/sounds/) for every app sound key.
 * Keep in sync with the outputs of scripts/generate-sounds.mjs.
 */
export const SOUND_FILES: Record<AppSoundKey, string> = {
  make: 'make.wav',
  miss: 'miss.wav',
  streak3: 'streak3.wav',
  streak5: 'streak5.wav',
  streak10: 'streak10.wav',
  session_start: 'session_start.wav',
  rim_locked: 'rim_locked.wav',
} as const;
